name: base_project_template
description: A new Flutter project.

version: 0.5.4+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  http: 0.12.1
  logger: ^0.9.1
  get_version: ^0.2.2
  google_fonts: ^1.1.0
  carousel_slider: ^2.3.1

  flutter_secure_storage: 3.2.1+1
  firebase_messaging: 7.0.3
  firebase_core: ^0.5.0+1
  firebase_database: ^4.1.1

  redux: ^4.0.0
  rxdart: ^0.24.1
  redux_epics: ^0.14.0
  flutter_redux: ^0.6.0
  flutter_redux_navigation: ^0.6.0

  data_connection_checker: ^0.3.4

  cached_network_image: 2.0.0
  url_launcher: ^5.7.2
  flutter_svg: ^0.19.0
  video_player: ^0.10.0
  pdf_flutter: ^1.1.3
  photo_view: 0.9.2
  share: ^0.6.5+3
  device_info: ^0.4.2+9

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 0.39.14
  build_resolvers: ^1.3.11
  json_serializable: 3.2.5
  build_runner: 1.10.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/mc_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/loading.svg
    - assets/svgs/logo.svg
    - assets/svg/mc_logo.svg
    - assets/svg/close.svg
    - assets/svg/back_arrow.svg
    - assets/svg/handle.svg
    - assets/svg/another_catalog.svg
    - assets/svg/home.svg
    - assets/svg/logout.svg
    - assets/svg/settings.svg
    - assets/svg/switch.svg
    - assets/png/mc_logo.png


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Light.ttf
        - asset: assets/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-Regular.ttf