name: my_catalog
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  http: 0.12.0+2
  logger: ^0.9.1
  get_version: ^0.2.2

  redux: ^4.0.0
  rxdart: ^0.24.1
  redux_epics: ^0.14.0
  flutter_redux: ^0.6.0
  flutter_redux_navigation: ^0.6.0

  data_connection_checker: ^0.3.4

  cached_network_image: 2.0.0

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 3.2.5
  build_runner: 1.7.2

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/loading_image.gif

  fonts:
    - family: BottomBar
      fonts:
        - asset: assets/icons/BottomBar.ttf
    - family: EXIL71
      fonts:
        - asset: assets/EXIL71.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/SFPD/SFProDisplay-Black.ttf
        - asset: assets/SFPD/SFProDisplay-Heavy.ttf
        - asset: assets/SFPD/SFProDisplay-Medium.ttf
        - asset: assets/SFPD/SFProDisplay-Regular.ttf
        - asset: assets/SFPD/SFProDisplay-Semibold.ttf
        - asset: assets/SFPD/SFProDisplay-Ultralight.ttf
        - asset: assets/SFPD/SFProDisplay-ThinItalic.ttf
          style: italic
        - asset: assets/SFPD/SFProDisplay-LightItalic.ttf
          style: italic
        - asset: assets/SFPD/SFProDisplay-BoldItalic.ttf
          style: italic